### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by astronomersiva** [astronomersiva/lego#1]
- [x] **[CRITICAL]** Figuring out a way to use layouts for md files.
- [x] **[CRITICAL]** Generate 404 from a given template
- [x] **[CRITICAL]** Should copy static to build/static.
- [x] **[CRITICAL]** Handling url-for in templates.
- [x] **[CRITICAL]** `pre` code tag fix
- [x] **[CRITICAL]** embedded svgs are broken
- [x] **[CRITICAL]** Run a server once the build is done
- [x] **[CRITICAL]** Documentation
- [x] **[CRITICAL]** Parallel task mechanism, a separate `build` task
- [x] Minify and uglify static files
- [x] Fingerprinting static files
- [x] Minifying html
- [x] Sync file changes and reload
- [x] Better logging
