### ISSUE TITLE
v3 Roadmap

### ISSUE THREAD

**Issue by astronomersiva** [astronomersiva/lego#120]
- [ ] Better logging
- [ ] Better error reports, especially for Nunjucks templates
- [ ] Pagination
- [ ] Pages in MD
- [ ] Refine responsive images
- [ ] Lazy loading images
- [ ] Bundle instant.page

**Comment by SetiZ** [comment]
Can I suggest Service Worker too? :)

**Comment by astronomersiva** [comment]
@SetiZ Thanks for the suggestion!

It would be great if you could put together a PR for this. I would be glad to help you out with the implementation. You can use this [PWABuilder site](https://www.pwabuilder.com/serviceworker) to get the SW code.

**Comment by AshotN** [comment]
Would it be possible for Lego to work with [Pug](https://github.com/pugjs/pug)

**Comment by arslabora** [comment]
I'll be glad to help. I'm quite impressed on this project, I like the minimalistic yet modern approach. My biggest concern, in regard static generators, is to have a sane multi-language implementation (i18n and l10n); also, having both global as well per-{post,page,type} asset is something I usually try to address. Custom types, of course, is a must.

So, I'm on a trip, right now, so I have limited access to code. Which is 'lego' status on those features?
